apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  selector:
    app: my-nginx
  ports:
    - name: my-nginxport
      protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
  externalIPs:
    - 192.168.0.195
