version: '3'
services:
  web:
    image: t9:latest
    container_name: tomcat-container
    ports:
     - "8888:8080"
    hostname: docker-tomcat
    #  volumes:
            # - ./webapps:/usr/local/tomcat/webapps
    links:
      - db:mysql
  db:
    restart: always
    container_name: mysql
    image: mysql:latest 
    environment:
     # MYSQL_USER: root
      MYSQL_DATABASE: tender
      MYSQL_ROOT_PASSWORD: sivakiran
      # MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
