apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  selector:
    app: tomcat
  ports:
    - name: mypot
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.168.0.195
    - 192.168.0.121
  selector:
    app: tomcat
    tier: frontend
